### ISSUE TITLE
Package it into something reusable/configurable

### ISSUE THREAD

**Issue by slarwise** [slarwise/version-promote#24]
- [ ] Configure paths to different environments
- [ ] Make it possible to group environments
- [ ] Configure if an environment is auto updated or not

**Comment by slarwise** [comment]
I think the most minimal thing would be an action like

```yaml
- uses: actions/update-image-version
  with:
    version: 0.0.2
    path: ./k8s/overlays/dev
    auto: true
- uses: actions/update-image-version
  with:
    version: 0.0.2
    path: ./k8s/overlays/prod
    auto: false
```

**Comment by slarwise** [comment]
One can make a workflow out of this that can take the version as input. Then we can use that workflow to rollback stuff by running it manually using something like workflow_dispatch.inputs.version. Only thing missing then is suggestions on what versions exist and what the different between the current version and the promoted/rollbacked version would be. The automatically created PR could print a changelog. Or that could be a separate action/workflow.

**Comment by slarwise** [comment]
A grouped version could look like:

```yaml
- uses: actions/update-image-version
  with:
    tag: $TAG
    image-repo: ghcr.io/slarwise/version-promote
    path: ./k8s/overlays/dev
    auto: true
- uses: actions/update-image-version
  with:
    group:
      tag: $TAG
      image-repo: ghcr.io/slarwise/version-promote
      auto: false
      paths:
        - ./k8s/overlays/qa
        - ./k8s/overlays/prod
```

**Comment by slarwise** [comment]
Or, in smaller pieces:

```yaml
- uses: actions/update-image-version
  with:
    name: dev
    tag: $TAG
    image-repo: ghcr.io/slarwise/version-promote
    path: ./k8s/overlays/dev
- name: Push to main
   run: |
    git config user.name bot
    git config user.email bot@github.com
    git commit -am "Update dev image to ${TAG}"
    git push
- name: Close any already open PR's
  run: |
    # Get PR's with branches matching prefix
    # Close them
- uses: actions/update-image-version
  with:
    name: prod
    tag: $TAG
    image-repo: ghcr.io/slarwise/version-promote
    path: ./k8s/overlays/prod
- name: Create PR
   run: |
    git config user.name bot
    git config user.email bot@github.com
    git checkout -b "promote/prod/${TAG}"
    git commit -am "Update prod image to ${TAG}"
    git push
    gr pr create --fill
```
